# Generated by Django 4.1.2 on 2022-10-24 07:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[users.models.User.validate_aadhar_no], verbose_name='Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[users.models.User.validate_phone_no], verbose_name='Phone number'),
        ),
    ]
